version: '3.8'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./backend:/app/:cached
    env_file: .env
    ports:
      - "${TRACKING_BACKEND_PORT}:${TRACKING_BACKEND_PORT}"
    command: uvicorn app.main:app --host 0.0.0.0 --port ${TRACKING_BACKEND_PORT} --reload
